# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('files', models.ImageField(upload_to=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=75)),
                ('logo', models.ImageField(upload_to=True)),
                ('nombre', models.CharField(max_length=140)),
                ('status', models.BooleanField(default=False)),
                ('tel', models.CharField(max_length=140)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='TipoNegocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiponegocio', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75)),
                ('nombre', models.CharField(max_length=140)),
                ('status', models.BooleanField(default=False)),
                ('tel', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='negocio',
            name='tiponegocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TipoNegocio'),
        ),
        migrations.AddField(
            model_name='album',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Negocio'),
        ),
    ]
